engines:
  duplication:
    exclude_paths:
      - "**.spec.js"
    enabled: true
    config:
      languages:
      - javascript
  eslint:
      config:
        config: .eslintrc.js
      enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.js"
